language: java
jdk: openjdk7

env:
  - DB=postgres
before_script:
  - psql -c 'create database bich_test;' -U postgres
script:
  mvn package -DdataSource.url=jdbc:postgresql:bich_test
              -DdataSource.username=postgres
              -DdataSource.password=""
