@startuml

title Битник подает заявку на путешествие

(*)  --> "Перейти на страницу поиска поездки"

--> === B1 ===
--> "Выбрать пункт отправления"
--> === B2 ===
=== B1 === --> "Выбрать пункт прибытия"
--> === B2 ===
=== B1 === --> "Выбрать дату путеществия"
--> === B2 ===

If "Список поездок не пуст" then
--> [Yes] "Выбрать путешествие"
--> "Подать заявку"
--> "Система сохраняет заявку"
else
--> [No] === B1 ===
Endif
"Система сохраняет заявку" -->(*)
@enduml