@startuml

actor Битник
actor Предприниматель

title Жизненный цикл заявки на место

Битник -> Предприниматель: Создать заявку
activate Предприниматель
Предприниматель --> Битник: Принять заявку
deactivate Предприниматель

alt Заявка подтверждена
    Битник -> Предприниматель: Оставить отзыв
    activate Предприниматель

    Предприниматель --> Битник

    deactivate Предприниматель
end
@enduml