@startuml

title Состояния заявки на путешествие

[*] --> Новая: Создание заявки

Новая --> Рассматривается
Рассматривается --> РассматриваетсяВодителем
РассматриваетсяВодителем --> Отклонена: Водитель отклонил свою часть путешествия
РассматриваетсяВодителем --> ВсеУтвердили: Водитель утвердил заявку
ВсеУтвердили --> Рассматривается: Нет
ВсеУтвердили --> Утверждена: Да

Утверждена --> ПроверяетсяБитником
Отклонена --> ПроверяетсяБитником
ПроверяетсяБитником --> Старая
Старая --> [*]

@enduml